/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface RROInterface extends utils.Interface {
  functions: {
    "avsList(uint256)": FunctionFragment;
    "avsRegistry(string)": FunctionFragment;
    "depositToAVS(string,uint256)": FunctionFragment;
    "getAllAVSs()": FunctionFragment;
    "getRiskScore(string)": FunctionFragment;
    "getUserBalance(address,string)": FunctionFragment;
    "owner()": FunctionFragment;
    "rebalance()": FunctionFragment;
    "registerAVS(string,uint8)": FunctionFragment;
    "setUserPreferences(uint8)": FunctionFragment;
    "updateRiskScore(string,uint8)": FunctionFragment;
    "userBalances(address,string)": FunctionFragment;
    "userPreferences(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "avsList"
      | "avsRegistry"
      | "depositToAVS"
      | "getAllAVSs"
      | "getRiskScore"
      | "getUserBalance"
      | "owner"
      | "rebalance"
      | "registerAVS"
      | "setUserPreferences"
      | "updateRiskScore"
      | "userBalances"
      | "userPreferences"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "avsList",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "avsRegistry",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "depositToAVS",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllAVSs",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRiskScore",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserBalance",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "rebalance", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerAVS",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setUserPreferences",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateRiskScore",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "userBalances",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "userPreferences",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(functionFragment: "avsList", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "avsRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositToAVS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAllAVSs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRiskScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "rebalance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerAVS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setUserPreferences",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateRiskScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userBalances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userPreferences",
    data: BytesLike
  ): Result;

  events: {
    "AVSRegistered(string,uint8)": EventFragment;
    "Rebalanced(address,string,string,uint256)": EventFragment;
    "RiskScoreUpdated(string,uint8)": EventFragment;
    "UserPrefsUpdated(address,uint8)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AVSRegistered"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Rebalanced"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RiskScoreUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UserPrefsUpdated"): EventFragment;
}

export interface AVSRegisteredEventObject {
  name: string;
  baseRiskScore: number;
}
export type AVSRegisteredEvent = TypedEvent<
  [string, number],
  AVSRegisteredEventObject
>;

export type AVSRegisteredEventFilter = TypedEventFilter<AVSRegisteredEvent>;

export interface RebalancedEventObject {
  user: string;
  fromAVS: string;
  toAVS: string;
  amount: BigNumber;
}
export type RebalancedEvent = TypedEvent<
  [string, string, string, BigNumber],
  RebalancedEventObject
>;

export type RebalancedEventFilter = TypedEventFilter<RebalancedEvent>;

export interface RiskScoreUpdatedEventObject {
  avsName: string;
  newRiskScore: number;
}
export type RiskScoreUpdatedEvent = TypedEvent<
  [string, number],
  RiskScoreUpdatedEventObject
>;

export type RiskScoreUpdatedEventFilter =
  TypedEventFilter<RiskScoreUpdatedEvent>;

export interface UserPrefsUpdatedEventObject {
  user: string;
  maxRiskScore: number;
}
export type UserPrefsUpdatedEvent = TypedEvent<
  [string, number],
  UserPrefsUpdatedEventObject
>;

export type UserPrefsUpdatedEventFilter =
  TypedEventFilter<UserPrefsUpdatedEvent>;

export interface RRO extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: RROInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    avsList(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    avsRegistry(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [string, number, boolean] & {
        name: string;
        baseRiskScore: number;
        exists: boolean;
      }
    >;

    depositToAVS(
      name: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getAllAVSs(overrides?: CallOverrides): Promise<[string[]]>;

    getRiskScore(
      name: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[number]>;

    getUserBalance(
      user: PromiseOrValue<string>,
      name: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    rebalance(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    registerAVS(
      name: PromiseOrValue<string>,
      baseRiskScore: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setUserPreferences(
      maxRiskScore: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateRiskScore(
      name: PromiseOrValue<string>,
      newRiskScore: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    userBalances(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    userPreferences(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [number, boolean] & { maxRiskScore: number; autoRebalance: boolean }
    >;
  };

  avsList(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  avsRegistry(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<
    [string, number, boolean] & {
      name: string;
      baseRiskScore: number;
      exists: boolean;
    }
  >;

  depositToAVS(
    name: PromiseOrValue<string>,
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getAllAVSs(overrides?: CallOverrides): Promise<string[]>;

  getRiskScore(
    name: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<number>;

  getUserBalance(
    user: PromiseOrValue<string>,
    name: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  owner(overrides?: CallOverrides): Promise<string>;

  rebalance(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  registerAVS(
    name: PromiseOrValue<string>,
    baseRiskScore: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setUserPreferences(
    maxRiskScore: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateRiskScore(
    name: PromiseOrValue<string>,
    newRiskScore: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  userBalances(
    arg0: PromiseOrValue<string>,
    arg1: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  userPreferences(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<
    [number, boolean] & { maxRiskScore: number; autoRebalance: boolean }
  >;

  callStatic: {
    avsList(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    avsRegistry(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [string, number, boolean] & {
        name: string;
        baseRiskScore: number;
        exists: boolean;
      }
    >;

    depositToAVS(
      name: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    getAllAVSs(overrides?: CallOverrides): Promise<string[]>;

    getRiskScore(
      name: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<number>;

    getUserBalance(
      user: PromiseOrValue<string>,
      name: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<string>;

    rebalance(overrides?: CallOverrides): Promise<void>;

    registerAVS(
      name: PromiseOrValue<string>,
      baseRiskScore: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setUserPreferences(
      maxRiskScore: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateRiskScore(
      name: PromiseOrValue<string>,
      newRiskScore: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    userBalances(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    userPreferences(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [number, boolean] & { maxRiskScore: number; autoRebalance: boolean }
    >;
  };

  filters: {
    "AVSRegistered(string,uint8)"(
      name?: null,
      baseRiskScore?: null
    ): AVSRegisteredEventFilter;
    AVSRegistered(name?: null, baseRiskScore?: null): AVSRegisteredEventFilter;

    "Rebalanced(address,string,string,uint256)"(
      user?: null,
      fromAVS?: null,
      toAVS?: null,
      amount?: null
    ): RebalancedEventFilter;
    Rebalanced(
      user?: null,
      fromAVS?: null,
      toAVS?: null,
      amount?: null
    ): RebalancedEventFilter;

    "RiskScoreUpdated(string,uint8)"(
      avsName?: null,
      newRiskScore?: null
    ): RiskScoreUpdatedEventFilter;
    RiskScoreUpdated(
      avsName?: null,
      newRiskScore?: null
    ): RiskScoreUpdatedEventFilter;

    "UserPrefsUpdated(address,uint8)"(
      user?: null,
      maxRiskScore?: null
    ): UserPrefsUpdatedEventFilter;
    UserPrefsUpdated(
      user?: null,
      maxRiskScore?: null
    ): UserPrefsUpdatedEventFilter;
  };

  estimateGas: {
    avsList(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    avsRegistry(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    depositToAVS(
      name: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getAllAVSs(overrides?: CallOverrides): Promise<BigNumber>;

    getRiskScore(
      name: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getUserBalance(
      user: PromiseOrValue<string>,
      name: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    rebalance(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    registerAVS(
      name: PromiseOrValue<string>,
      baseRiskScore: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setUserPreferences(
      maxRiskScore: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateRiskScore(
      name: PromiseOrValue<string>,
      newRiskScore: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    userBalances(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    userPreferences(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    avsList(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    avsRegistry(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    depositToAVS(
      name: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getAllAVSs(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getRiskScore(
      name: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getUserBalance(
      user: PromiseOrValue<string>,
      name: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    rebalance(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    registerAVS(
      name: PromiseOrValue<string>,
      baseRiskScore: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setUserPreferences(
      maxRiskScore: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateRiskScore(
      name: PromiseOrValue<string>,
      newRiskScore: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    userBalances(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    userPreferences(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
